### PR TITLE
Flowstorm debugger

### PR DESCRIPTION
**Pull request by dmg46664**
Alias to include the Flow Storm debug tool - A tracing debugger for Clojure and ClojureScript

https://github.com/jpmonettas/flow-storm-debugger

### CODE REVIEW

**Comment by practicalli-john** [comment]
Thanks.  I will take a look when I am back at a big screen -the text in the demo video is tiny 🤣

As it's adding a library rather than running a tool, I prefix these with`lib`.

So the alias would be `:lib/flowstorm`

I'll take a look at the video though and see if that still makes sense

The video did mention two dependencies to use flowstorm, but I couldn't see what they were (maybe one was Clojure itself...)

**Comment by dmg46664** [comment]
Thanks for taking a look.
It actually is a tool, but I'm unsure whether to bundle it as such or whether that limits the ability to configure nrepl/cider etc.
Perhaps it should have both options?

I was able to get it to work with only that dependency, despite bits and pieces in the docs.

**Comment by practicalli-john** [comment]
From my limited understanding it seems there is a need for 2 aliases as there are 2 different flowstorm libraries, one for Clojure and one for ClojureScript (which seems only works with shadow-cljs though)

https://github.com/jpmonettas/flow-storm-debugger/#artifacts

So a `:lib/flowstorm-cljs`should also be added for completenese

I haven't seen the docs about nrepl config yet.  The demo suggests that is not required, but that wasn't clearly shown.  So including the aliases via the `:lib/` domain is the consistent choice 

> If some nrepl middleware is mandatory then flowstorm would need to use a `:repl/` domain instead

Although much of the step debug features can be done with cider-debug, there are additional debug features in flowstorm that could be useful.  There are some interesting features that go beyond the cider-inspector too.

And of course for those not using Emacs Cider then it provides a debug tool

I'll try carve out time to test the aliases in the next few days, thanks

**Comment by dmg46664** [comment]
@practicalli-john What I particularly appreciated about the tool was to easily instrument a number of functions in a stack that I wasn't  familiar with (it keeps them in a list which can be enabled and disabled). This let me explore without having to track the instrumented list in my head. The ability to re-run complex functions with their arguments was also useful.

An aside: I do regard _needing_ to use a tool like this as a code smell on a code base!

However, even if it wasn't novel, I'd hope that any considerable tool made it into `clojure-deps-edn` as even lesser used options shouldn't bother anyone (except maintainers) and allows for experimentation.

**Pull request merged**
