### PR TITLE
Add replace-paths to aliases using replace-deps

### PR DESCRIPTION
**Pull request by imrekoszo**
A user.clj or data_readers.clj on the project path might affect the operation of the tool unless the project's paths are overridden. See also: https://ask.clojure.org/index.php/9857/could-option-that-variant-sdeps-avoid-having-specify-alias?show=9884#a9884

### CODE REVIEW

**Comment by jr0cket** [comment]
Hmm, this is an interesting potential situation.  I would like to explore a few scenarios around this before adding this change.  It seems unusual to add empty paths, as you mentioned in the Ask Clojure discussion.

Do you have any example projects you can share that would exhibit incorrect behaviour?

I will try and create some scenarios at the next opportunity for testing purposes.

Thank you.

**Comment by imrekoszo** [comment]
> Do you have any example projects you can share that would exhibit incorrect behaviour?

Sure, take this repo for example: https://github.com/imrekoszo/depslink3_2#missing-replace-paths-repro-case

No replace-paths:
```
> clojure -Srepro -Sdeps '{:aliases {:blank {:replace-deps {}}}}' -M:blank

Exception in thread "main" Syntax error compiling at (user.clj:1:1).
	at clojure.lang.Compiler.load(Compiler.java:7648)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:368)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:364)
	at clojure.lang.RT.doInit(RT.java:486)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.main.main(main.java:38)
Caused by: java.io.FileNotFoundException: Could not locate net/cgrand/xforms__init.class, net/cgrand/xforms.clj or net/cgrand/xforms.cljc on classpath.
	at clojure.lang.RT.load(RT.java:462)...
```

Replace-paths:
```
> clojure -Srepro -Sdeps '{:aliases {:blank {:replace-deps {} :replace-paths []}}}' -M:blank
Clojure 1.10.1
user=>
```

**Comment by imrekoszo** [comment]
My reasoning here is that if your tool invocation dumps all the deps of a project with `:replace-deps`, you shouldn't expect to be able to load any namespaces of said project as they could require something you dumped. There are two cases from here:

1 - the tool never intended to load namespaces from the project in the first place. In this case, `:replace-paths` gives a safety net around this, as some namespaces, [like user.clj](https://clojureverse.org/t/how-are-user-clj-files-loaded/3842/2?u=imrekoszo) are automatically loaded by Clojure if they are found on the classpath, even if they weren't meant to be loaded, potentially causing unexpected behaviour or preventing the tool from running. This was something I ran into when trying to use `:project/outdated` on such a project, and reproed with [uberdeps](https://github.com/tonsky/uberdeps/pull/36).

2 - the tool wants to load namespaces from the project. In this case `:extra-deps` should be used instead so there is a smaller chance that you aren't loading a dep that one of those namespaces depends on.

**Comment by jr0cket** [comment]
After looking at the code, I've noticed that antq is not updating aliases with `:replace-deps`, so just working on that issue and will look at this on Monday hopefully.

Thanks for the extra information, it will be very useful for my tests.

**Comment by jr0cket** [comment]
I would prefer to keep this change separate from the library version update if possible.  If you can remove the uberdeps library version increase from this change from the PR I will accept it.

Thanks again, this has been most enlightening

**Comment by imrekoszo** [comment]
> remove the uberdeps library version increase

That's done now, thank you

**Comment by jr0cket** [comment]
Pull request merged, thank you

I updated the description for a bit more clarity.  I also edited the change to put the `replace-paths` first, as it seems easier to read and understand that way.  Its also the same order of the top level keys, `:path` then `:deps`.

Thanks again.

**Comment by jr0cket** [comment]
After further testing, I've switched back several aliases to use extra-paths and removed replace-paths, e.g jar, uberjar.

**Comment by imrekoszo** [comment]
> After further testing, I've switched back several aliases to use extra-paths and removed replace-paths, e.g jar, uberjar.

Interesting. I never used depstar so wouldn't be able to comment on that. Uberdeps, however, should be used with replace-deps/paths: https://github.com/tonsky/uberdeps#no-config-setup

**Pull request merged**
