### PR TITLE
Add :lint/cljfmt

### PR DESCRIPTION
**Pull request by joshrotenberg**
Another quick one, adds the `:lint/cljfmt` target to find/fix formatting issues.

### CODE REVIEW

**Comment by joshrotenberg** [comment]
Whoops, didn't see that there was already a `format`. Moved there.

**Comment by practicalli-john** [comment]
The cljfmt documentation states that either the `check` or `fix` command should be passed to the main function as an argument.  Do you know what happens if neither of these are passed?

Are you assuming that either `check` or `fix` will be passed on the command line when using this alias?

Otherwise, perhaps its useful to add aliases for both commands:

I assume something like this
```clojure
  :format/cljfmt
  {:extra-deps {cljfmt/cljfmt {:mvn/version "0.8.0"}}
   :main-opts ["-m" "cljfmt.main" "check"]}

  :format/cljfmt-fix
  {:extra-deps {cljfmt/cljfmt {:mvn/version "0.8.0"}}
   :main-opts ["-m" "cljfmt.main" "fix"]}



```

**Comment by joshrotenberg** [comment]
With no arguments it just prints out the help for `cljfmt` which I do think is useful. It does, however, look like `--help` works with check and fix: 

```shell
❯ clj -M:format fix --help
cljfmt [OPTIONS] COMMAND [PATHS ...]
      --help
      --file-pattern FILE_PATTERN                  \.clj[csx]?$
      --indents INDENTS_PATH
      --alias-map ALIAS_MAP_PATH
      --project-root PROJECT_ROOT                  .
      --[no-]ansi
      --[no-]indentation
      --[no-]remove-multiple-non-indenting-spaces
      --[no-]remove-surrounding-whitespace
      --[no-]remove-trailing-whitespace
      --[no-]insert-missing-whitespace
      --[no-]remove-consecutive-blank-lines

# and 

❯ clj -M:format check --help
cljfmt [OPTIONS] COMMAND [PATHS ...]
      --help
      --file-pattern FILE_PATTERN                  \.clj[csx]?$
      --indents INDENTS_PATH
      --alias-map ALIAS_MAP_PATH
      --project-root PROJECT_ROOT                  .
      --[no-]ansi
      --[no-]indentation
      --[no-]remove-multiple-non-indenting-spaces
      --[no-]remove-surrounding-whitespace
      --[no-]remove-trailing-whitespace
      --[no-]insert-missing-whitespace
      --[no-]remove-consecutive-blank-lines
```

So I think that probably makes sense to fix. I'll make it happen.

**Comment by practicalli-john** [comment]
Thank you.

**Pull request merged**
