### PR TITLE
Fix markdown lint

### PR DESCRIPTION
**Pull request by joshrotenberg**
Looks like the markdown lint action wasn't working. This should fix the listing, but it does still fail with some listing errors from the README.

### CODE REVIEW

**Comment by practicalli-john** [comment]
I didn't get chance to try the markdown linter locally, but hopefully will today.

If we don't get this working, I think I have a linter I used for another project that seems to work okay.

Thanks.

**Comment by practicalli-john** [comment]
The linter I have used on my books seems to work well, an example of the action that uses it is here - hopefully the github workflow yaml is not too messy :)

https://github.com/practicalli/clojure/blob/master/.github/workflows/linter.yml

There is also a configuration file I use with this to configure some of the options

https://github.com/practicalli/clojure/blob/master/.github/linters/.markdown-lint.yml

I am inclined to use the same linter for all the practicalli projects, unless there linter suggested in this PR is noticeably nicer to work with

**Comment by joshrotenberg** [comment]
> I am inclined to use the same linter for all the practicalli projects, unless there linter suggested in this PR is noticeably nicer to work with

If you already have something you like, definitely go with that. I just tried a few from the marketplace and this one worked ok. I'm happy to help out if I can.

**Comment by practicalli-john** [comment]
I am going to remove the markdownlint action and replace with superlint, which seems to work very well and covers a number of linters.  Thank you for prompting me to add more linter coverage.

**Pull request closed without merging**
