### PR TITLE
deps: add `:lib/neil` alias

### PR DESCRIPTION
**Pull request by deas**
neil is a CLI to add common aliases and features to deps.edn-based projects.

Added `:lib/neil` alias which requires a specific command

### CODE REVIEW

**Comment by practicalli-john** [comment]
I have been thinking about this for a while in the background.  I always assumed that neil was best used as its own tool.

If there use cases where :lib/neil would be used with other aliases in practicalli/clojure-deps-edn or with aliases from a project deps.edn file then its worth adding.

If neil is better used as its own tool, then I would rather omit it and not have to maintain the additional alias.

Let me know. 
Thanks.

**Comment by deas** [comment]
I'd say in general it fits here. However, I understand we may not want to maintain versions in this repo.

Meanwhile, I build another slightly different `neil` thing which gets around the versioning a bit: https://github.com/deas/asdf-neil

IIRC, @borkdude recently came up with another thing targeting reusable/shareable babashka scripts.

**Comment by borkdude** [comment]
The above can be useful for when people cannot or will not use bb but rather run everything in a JVM.

**Comment by practicalli-john** [comment]
I cant imagine anyone would not want to use babashka 😸 However, it seems a valid use case so I will merge soon (after I have cleaned up the formatting and a few other bits)

Thank you.

**Comment by practicalli-john** [comment]
Thank you.

**Pull request merged**
